# Generated by Django 5.0.1 on 2025-01-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitionerdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableslot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
