# Generated by Django 4.2 on 2026-02-02 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patientdashboard', '0005_auto_20260121_1102'),
        ('user_account', '0001_initial'),
        ('practitionerdashboard', '0002_practitionernotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availableslot',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='availableslot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='availableslot',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='practitionernotification',
            name='notification_type',
            field=models.CharField(default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='practitionernotification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='user_account.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='availableslot',
            unique_together={('practitioner', 'date', 'start_time')},
        ),
        migrations.CreateModel(
            name='SocialSecurityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('social_security', 'Social Security'), ('insurance', 'Insurance'), ('private', 'Private Payment'), ('copay', 'Co-payment'), ('deductible', 'Deductible')], default='social_security', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('covered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('patient_copay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ss_number', models.CharField(blank=True, help_text="Patient's Social Security Number", max_length=20, null=True)),
                ('insurance_number', models.CharField(blank=True, help_text='Insurance Policy Number', max_length=50, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis_code', models.CharField(blank=True, help_text='ICD-10 Diagnosis Code', max_length=20, null=True)),
                ('procedure_code', models.CharField(blank=True, help_text='CPT Procedure Code', max_length=20, null=True)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reimbursed', 'Reimbursed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pre_authorization_code', models.CharField(blank=True, max_length=50, null=True)),
                ('referral_number', models.CharField(blank=True, max_length=50, null=True)),
                ('eligibility_verified', models.BooleanField(default=False)),
                ('eligibility_verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ss_payments', to='patientdashboard.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.practitioner')),
            ],
            options={
                'verbose_name': 'Social Security Payment',
                'verbose_name_plural': 'Social Security Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge'), ('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('writeoff', 'Write-off')], max_length=20)),
                ('transaction_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('insurance', 'Insurance Payment'), ('social_security', 'Social Security')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('check_number', models.CharField(blank=True, max_length=50, null=True)),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('processed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='practitionerdashboard.socialsecuritypayment')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('insurance_card', 'Insurance Card'), ('ss_card', 'Social Security Card'), ('id_verification', 'ID Verification'), ('pre_auth', 'Pre-Authorization'), ('claim_form', 'Claim Form'), ('receipt', 'Payment Receipt'), ('eob', 'Explanation of Benefits')], max_length=20)),
                ('file', models.FileField(upload_to='payment_documents/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='practitionerdashboard.socialsecuritypayment')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('not_eligible', 'Not Eligible'), ('expired', 'Expired'), ('error', 'Verification Error')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('coverage_start_date', models.DateField(blank=True, null=True)),
                ('coverage_end_date', models.DateField(blank=True, null=True)),
                ('coverage_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('deductible_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductible_met', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('verification_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='practitionerdashboard.socialsecuritypayment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='availableslot',
            name='day_of_week',
        ),
    ]
