# Generated by Django 5.0.1 on 2025-01-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitionerdashboard', '0002_availableslot_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableslot',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='availableslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=10),
        ),
    ]
