# Generated by Django 4.2 on 2026-02-10 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
        ('practitionerdashboard', '0003_alter_availableslot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('no_show', 'Repeated No-Shows'), ('late_cancellation', 'Repeated Late Cancellations'), ('inappropriate_behavior', 'Inappropriate Behavior'), ('non_payment', 'Non-Payment Issues'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Detailed reason for blacklisting')),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_permanent', models.BooleanField(default=True)),
                ('unblock_date', models.DateField(blank=True, help_text='Date when patient will be automatically unblocked', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_by', to='user_account.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_patients', to='user_account.practitioner')),
            ],
            options={
                'verbose_name': 'Patient Blacklist',
                'verbose_name_plural': 'Patient Blacklists',
                'ordering': ['-blacklisted_at'],
                'unique_together': {('practitioner', 'patient')},
            },
        ),
    ]
