# Generated by Django 5.1.4 on 2025-03-28 02:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitionerdashboard', '0004_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableslot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
