# Generated by Django 5.1.4 on 2025-03-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitionerdashboard', '0005_availableslot_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableslot',
            name='day_of_week',
        ),
        migrations.AlterField(
            model_name='availableslot',
            name='date',
            field=models.DateField(),
        ),
    ]
