# Generated by Django 5.1.4 on 2025-03-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitionerdashboard', '0006_remove_availableslot_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableslot',
            name='day_of_week',
            field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
