# Generated by Django 5.0.1 on 2025-02-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_ai_config_chatroom_ai_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
