# Generated by Django 5.0.1 on 2025-02-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_is_ai_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='ai_config',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='ai_enabled',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_ai_generated',
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('practitioner', 'Practitioner')], max_length=20),
        ),
    ]
