<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-02-11 20:56

import django.db.models.deletion
=======
# Generated by Django 5.0.1 on 2025-01-22 10:09

import django.db.models.deletion
import django.utils.timezone
>>>>>>> 17ea03e8f340c1f1666283f9290a53227939a329
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('practitionerdashboard', '0004_prescription'),
=======
        ('practitionerdashboard', '0001_initial'),
>>>>>>> 17ea03e8f340c1f1666283f9290a53227939a329
        ('user_account', '0005_practitioner_gender_practitioner_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='user_account.patient')),
                ('practitioner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='user_account.practitioner')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='practitionerdashboard.availableslot')),
=======
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='user_account.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='user_account.practitioner')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='practitionerdashboard.availableslot')),
>>>>>>> 17ea03e8f340c1f1666283f9290a53227939a329
            ],
        ),
    ]
