# Generated by Django 5.0.1 on 2025-01-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientdashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
