# Generated by Django 5.0.1 on 2025-01-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientdashboard', '0004_delete_appointment'),
        ('practitionerdashboard', '0003_remove_availableslot_is_booked_availableslot_status'),
        ('user_account', '0005_practitioner_gender_practitioner_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='user_account.patient')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='practitionerdashboard.availableslot')),
            ],
        ),
    ]
