# Generated by Django 5.1.4 on 2025-01-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientdashboard', '0006_appointment_practitioner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='practitioner',
        ),
    ]
