# Generated by Django 5.1.4 on 2025-07-07 20:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdashboard', '0016_appointment_amount_appointment_payment_id_and_more'),
        ('practitionerdashboard', '0007_availableslot_day_of_week'),
        ('user_account', '0005_practitioner_gender_practitioner_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='patientdashboard.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.practitioner')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practitionerdashboard.availableslot')),
            ],
        ),
    ]
