# Generated by Django 5.1.4 on 2025-07-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientdashboard', '0022_symptom_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='patient',
        ),
    ]
