# Generated by Django 5.1.4 on 2025-07-28 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdashboard', '0024_symptom_patient'),
        ('user_account', '0007_alter_patient_greeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.patient'),
        ),
    ]
