# Generated by Django 5.1.4 on 2025-01-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(choices=[('Mr.', 'Mr.'), ('Other', 'Other')], max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=10)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_type', models.CharField(choices=[('health_professional', 'A health professional'), ('other', 'Other')], max_length=20)),
                ('specialty', models.CharField(choices=[('occupational_therapist', 'Occupational Therapist'), ('physiotherapist', 'Masseur(sseuse) Physiotherapist'), ('masseur_physiotherapist', 'Masseur(sseuse)-Physiotherapist'), ('neuropsychologist', 'Neuropsychologist'), ('speech_therapist', 'Speech Therapist'), ('psychologist', 'Psychologist'), ('chiropractor', 'Chiropractor'), ('nutritionist', 'Nutritionist'), ('general_practitioner', 'General Practitioner')], max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('civility', models.CharField(choices=[('m', 'M.'), ('mme', 'Mme'), ('mlle', 'Mlle')], max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('terms_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
