# Generated by Django 5.0.1 on 2025-01-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_patient_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='specialty',
            field=models.CharField(choices=[('occupational_therapist', 'Occupational Therapist'), ('physiotherapist', 'Physiotherapist'), ('neuropsychologist', 'Neuropsychologist'), ('speech_therapist', 'Speech Therapist'), ('psychologist', 'Psychologist'), ('chiropractor', 'Chiropractor'), ('nutritionist', 'Nutritionist'), ('general_practitioner', 'General Practitioner')], max_length=30),
        ),
    ]
