# Generated by Django 5.1.4 on 2025-07-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_practitioner_gender_practitioner_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='greeting',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs', 'Mrs')], max_length=5),
        ),
    ]
