# Generated by Django 5.1.4 on 2025-07-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_alter_patient_greeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='greeting',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs', 'Mrs')], max_length=5, null=True),
        ),
    ]
